export const COUNTRY_OPTIONS = [
  // Latinoamérica y España
  { code: 'ES', label: 'España' },
  { code: 'MX', label: 'México' },
  { code: 'AR', label: 'Argentina' },
  { code: 'CO', label: 'Colombia' },
  { code: 'US', label: 'EEUU' },
  { code: 'PE', label: 'Perú' },
  { code: 'CL', label: 'Chile' },
  { code: 'EC', label: 'Ecuador' },
  { code: 'VE', label: 'Venezuela' },
  { code: 'UY', label: 'Uruguay' },
  { code: 'PY', label: 'Paraguay' },
  { code: 'BO', label: 'Bolivia' },
  { code: 'CR', label: 'Costa Rica' },
  { code: 'PA', label: 'Panamá' },
  { code: 'DO', label: 'Rep. Dominicana' },
  { code: 'GT', label: 'Guatemala' },
  { code: 'HN', label: 'Honduras' },
  { code: 'SV', label: 'El Salvador' },
  { code: 'NI', label: 'Nicaragua' },
  { code: 'CU', label: 'Cuba' },
  { code: 'PR', label: 'Puerto Rico' },
  // Europa
  { code: 'BR', label: 'Brasil' },
  { code: 'PT', label: 'Portugal' },
  { code: 'FR', label: 'Francia' },
  { code: 'DE', label: 'Alemania' },
  { code: 'IT', label: 'Italia' },
  { code: 'GB', label: 'Reino Unido' },
  { code: 'NL', label: 'Países Bajos' },
  { code: 'BE', label: 'Bélgica' },
  { code: 'CH', label: 'Suiza' },
  { code: 'AT', label: 'Austria' },
  { code: 'SE', label: 'Suecia' },
  { code: 'NO', label: 'Noruega' },
  { code: 'DK', label: 'Dinamarca' },
  { code: 'FI', label: 'Finlandia' },
  { code: 'PL', label: 'Polonia' },
  { code: 'IE', label: 'Irlanda' },
  { code: 'RO', label: 'Rumanía' },
  { code: 'GR', label: 'Grecia' },
  { code: 'CZ', label: 'Chequia' },
  { code: 'HU', label: 'Hungría' },
  // Norteamérica
  { code: 'CA', label: 'Canadá' },
  // Asia y Oceanía
  { code: 'AU', label: 'Australia' },
  { code: 'NZ', label: 'Nueva Zelanda' },
  { code: 'JP', label: 'Japón' },
  { code: 'KR', label: 'Corea del Sur' },
  { code: 'IN', label: 'India' },
  { code: 'SG', label: 'Singapur' },
  { code: 'PH', label: 'Filipinas' },
  { code: 'TH', label: 'Tailandia' },
  { code: 'MY', label: 'Malasia' },
  { code: 'ID', label: 'Indonesia' },
  { code: 'AE', label: 'Emiratos Árabes' },
  { code: 'SA', label: 'Arabia Saudí' },
  { code: 'IL', label: 'Israel' },
  { code: 'TR', label: 'Turquía' },
  // África
  { code: 'ZA', label: 'Sudáfrica' },
  { code: 'NG', label: 'Nigeria' },
  { code: 'EG', label: 'Egipto' },
  { code: 'MA', label: 'Marruecos' },
  { code: 'KE', label: 'Kenia' },
] as const

export type CountryCode = (typeof COUNTRY_OPTIONS)[number]['code']
